version: '3'

services:
  app:
    image: node:16.6.0
    volumes:
      - ..:/usr/src/app:cached
      - ~/.ssh:/home/node/.ssh
    environment:
      NODE_ENV: development
      # BASEURL: 'test'
    ports:
      - "3000:3000"
    command: sleep infinity
    restart: unless-stopped
